version: '3.1'
services:
    info:
      build: ./info/
      ports:
          - '5000:5000'
      volumes:
          - ./info/:/code
      depends_on:
          - mongo
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example

    lookup:
      build: ./lookup/
      ports:
          - '8000:8000'
      volumes:
          - ./info/:/code
      depends_on:
          - info

    mongo:
      image: mongo:3.6
      restart: always
      ports:
          - '27017:27017'
      environment:
        MONGO_INITDB_DATABASE: movielab-info
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example